service: ezrealblindado-serverless

plugins:
  - serverless-bundle

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  
functions:
  greeting:
    handler: src/handlers/greeting.handler
    events:
      - http:
          method: GET
          path: /greeting
